# Generated by Django 4.1.1 on 2022-11-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='imagem', upload_to='imagens/'),
        ),
    ]
